---
codecov:
  require_ci_to_pass: yes  # yamllint disable-line rule:truthy
  notify:
    wait_for_ci: yes  # yamllint disable-line rule:truthy
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%
...
