name: Proxy.py

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python: [3.6, 3.7]
      max-parallel: 4
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-testing.txt
      - name: Quality Check
        run: |
          # The GitHub editor is 127 chars wide
          # W504 screams for line break after binary operators
          flake8 --ignore=W504 --max-line-length=127 proxy.py tests.py
          # mypy compliance check
          mypy --strict --ignore-missing-imports proxy.py plugin_examples.py tests.py
      - name: Run Tests
        run: pytest tests.py
