---
name: brew

on:   # yamllint disable-line rule:truthy
  push:
    paths:
    - 'proxy/**'
    - 'tests/**'
    - 'examples/**'
    - '.github/workflows/test-brew.yml'
  pull_request:
    paths:
    - 'proxy/**'
    - 'tests/**'
    - 'examples/**'
    - '.github/workflows/test-brew.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    name: 🐍${{ matrix.python }} @ ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS]
        python: ['3.10']
      max-parallel: 1
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Brew
      run: |
        brew install ./helper/homebrew/develop/proxy.rb
    - name: Verify
      run: |
        proxy -h
...
