name: Proxy.py Docker

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Build docker using ${{ matrix.python }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.7]
      max-parallel: 1
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          make container
