name: Proxy.py

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS, ubuntu, windows]
        python: [3.6, 3.7]
      max-parallel: 4
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}-dev
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-testing.txt
      - name: Quality Check
        run: |
          # W504 screams for line break after binary operators
          flake8 --ignore=W504 --max-line-length=127 proxy.py plugin_examples.py tests.py setup.py
          mypy --strict --ignore-missing-imports proxy.py plugin_examples.py tests.py setup.py
      - name: Run Tests
        run: |
          coverage3 run --source=proxy,plugin_examples tests.py
          coveralls --output=coverage.info
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
          architecture: 'x64'
      - name: Generate LCOV
        run: |
          gem install coveralls-lcov
          coveralls-lcov -v -n coverage.info > coverage.json
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.json
          parallel: true
