---
name: docker

on:   # yamllint disable-line rule:truthy
  push:
    paths:
    - 'proxy/**'
    - 'tests/**'
    - 'examples/**'
    - 'requirements*'
    - 'setup.cfg'
    - 'check.py'
    - 'MANIFEST.in'
    - '.github/workflows/test-docker.yml'
    - 'Dockerfile'
  pull_request:
    paths:
    - 'proxy/**'
    - 'tests/**'
    - 'examples/**'
    - 'requirements*'
    - 'setup.cfg'
    - 'check.py'
    - 'MANIFEST.in'
    - '.github/workflows/test-docker.yml'
    - 'Dockerfile'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    name: 🐍${{ matrix.python }} @ ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu]
        python: ['3.10']
      max-parallel: 1
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-release.txt
        pip install -r requirements-testing.txt
        pip install -r requirements-tunnel.txt
    - name: Build
      run: |
        make container
...
