name: Proxy.py Integration

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    name: Integration - Python ${{ matrix.python }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS, ubuntu, windows]
        python: [3.5, 3.6, 3.7, 3.8]
      max-parallel: 4
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Package
        run: python setup.py install
      - name: Start Proxy.py in Background (Windows Only)
        if: matrix.os == 'windows'
        run: START /B proxy > proxy.log
      - name: Start Proxy.py in Background
        if: matrix.os != 'windows'
        run: proxy --enable-web-server --pid-file /tmp/proxy.pid &
      - name: Run Integration Tests
        run: ./tests/integration/main.sh
